name: rspec-dev

channels:
    - defaults
    - conda-forge

dependencies:
    # build tools
    - bumpversion
    - twine

    # core
    - python=3.6

    # numeric dependency
    - numpy
    
    # native libraries
